### ISSUE TITLE
How it use?

### ISSUE THREAD

**Issue by plyaskin** [funktechno/kanboard-plugin-wiki#18]
Sorry, but I don't understand how I can to add the page, I don't have any button just about that I don't have any articles (There are no Wiki pages that you have access to), could you explain?

**Comment by lastlink** [comment]
Need more information.
This is a plugin for kanboard.net which is php based. If you don't have that installed then this won't work.

**Comment by lastlink** [comment]
Closing as the person hasn't responded or updated their information.
