### ISSUE TITLE
Left-aligned text in the wiki menu

### ISSUE THREAD

**Issue by deecey** [funktechno/kanboard-plugin-wiki#26]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement

### Actual behaviour
In the left menu in the Wikipage overview, the text is centered.

### Expected behaviour
For better readability, the text should be left-aligned while the trashcan symbol should be right-aligned.

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:
- Application settings Language:

**Comment by beneton2003** [comment]
Centered text is bad idea in left menu, we need left, can anyone please do it?
