### ISSUE TITLE
 Table of contents for Wikipages with section links

### ISSUE THREAD

**Issue by deecey** [funktechno/kanboard-plugin-wiki#27]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement

### Actual behaviour
Currently there is no table of contents for Wikipages, which makes longer pages confusing. At the same time, the block with the versioning information takes up a lot of space.

### Expected behaviour
There is a table of contents, e.g. as soon as there are more than three sections on the page. Clicking on one of the headings will take you to the appropriate section. The block with the version information is presented e.g. not as a list but side by side and in a smaller font.

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:
- Application settings Language:

**Comment by lastlink** [comment]
It sounds like it would be possible to implement a default page to use as the table of contents. Then you could use markdown to style your sections.

**Comment by deecey** [comment]
I am not sure if I understood your comment correctly. I meant something like the table of contents of Wikipedia articles. Don't know how that could work with the default page. But that would be a new page that does not exist in the current Wikipages version, right?

**Comment by lastlink** [comment]
They are supposed to be markdown compliant that does have links/anchors using headers. e.g. https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers

**Comment by deecey** [comment]
Okay, that means I can write a common article with headings and these are then used as the basis for the table of contents. Yes, that would be great :-) 👍

**Comment by lastlink** [comment]
You can create a manual table of conrtents. This is usually what I do, home page, 

## tob
* item 1
* item 2
* etc
