### ISSUE TITLE
Drag and drop of page order withdraws when page is reloaded

### ISSUE THREAD

**Issue by deecey** [funktechno/kanboard-plugin-wiki#28]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
In the left menu, the order of the individual pages can be changed by drag and drop. However, if you then click on one of the pages, the list will be sorted again in the order in which the pages were created.

### Expected behaviour
Changing the order should be preserved even if the page is reloaded.

### Configuration

- Kanboard version:
- Database type and version:
- PHP version:
- OS:
- Browser:
- Application settings Language:

**Comment by lastlink** [comment]
this is a pending feature planned to be implemented. Data schema was setup to support it and ui mocks what it should do, but the save change of page reordering hasn't been implemented yet.

**Comment by lastlink** [comment]
yeah still not working, would have to do some ajax with the token to update or do it in php.

**Comment by lastlink** [comment]
feature now complete and pending release https://github.com/kanboard/website/pull/511
