### ISSUE TITLE
maybe I am missing it - global search for wiki pages

### ISSUE THREAD

**Issue by biffbaxter** [funktechno/kanboard-plugin-wiki#29]
This issue is: I am uncertain of the syntax for global wikipage search. I have tried comment, content, wiki, wikipage, etc. Not sure if its implemented, but it appears to be closed as an issue and checked..but did not see an example of a search filter to reproduce, so unsure if its an end user issue (me) or not...ha

- [ ] Bug report
- [ ] Feature request
- [ ] Improvement
- [x] Not sure
### Configuration

- Kanboard version: latest (via docker)
- Database type and version: sqlite
- PHP version:
- OS: Arch Linux
- Browser: Vivaldi
- Application settings Language:

**Comment by biffbaxter** [comment]
Ehhh...sorry. nevermind. It appears that its at "project management --->wiki overview--->then you can search content it appears. Apologies and thank you!

**Comment by lastlink** [comment]
ref #5
