### ISSUE TITLE
Attachment FileModel can't initialize

### ISSUE THREAD

**Issue by comete-upn** [funktechno/kanboard-plugin-wiki#3]
Hello,

Thanks for this plugin.

We have an issue when using attachment files in a Wiki. It produces this error:

```
PHP message: PHP Fatal error:  Class 'Kanboard\Plugin\Wiki\Model\FileModel'
not found in plugins/Wiki/Model/WikiFile.php on line 11
```

Line 11 is the class definition: `class WikiFileModel extends FileModel`.

Is it because of the namespace?

Regards.

**Comment by lastlink** [comment]
Currently attachments don't work, they are a pending feature.

**Comment by brianneve** [comment]
End of year. Or earlier if I understand   
class WikiFileModel extends FileModel ....

**Comment by creecros** [comment]
#19 Adds File attachments.
