### ISSUE TITLE
Show project name in page titles

### ISSUE THREAD

**Issue by locness3** [funktechno/kanboard-plugin-wiki#36]
This issue is:

- [ ] Bug report
- [ ] Feature request
- [x] Improvement

I'd like the project name to be shown in the page titles when viewing the wiki for a project. This would also show it in the header of the page.

### Configuration

- Kanboard version: 1.2.10
- Database type and version: mysql,  10.1.38-MariaDB-0+deb9u1
- PHP version: 7.0.33-14+0~20191218.25+debian9~1.gbpae1889
- OS: macOS 10.11.6
- Browser: Firefox 76

**Comment by locness3** [comment]
Can someone direct me to where I can implement it?

**Comment by aljawaid** [comment]
> Can someone direct me to where I can implement it?


Hello, I needed this too.... took a while but I figured it out somehow...

**Change:**

https://github.com/funktechno/kanboard-plugin-wiki/blob/b1a141a41ba4c0056b1a2d90187e9194e19c4a78/Controller/WikiController.php#L69

**To:**
```
'title' => $project['name'] .= " ". t('Wiki'),
```

**Comment by locness3** [comment]
Please do a pull request
