### ISSUE TITLE
SQL Error: SQLSTATE[HY000]

### ISSUE THREAD

**Issue by carlosnewmusic** [funktechno/kanboard-plugin-wiki#39]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x84\x0D\x0A...' for column 'content' at row 1

### Expected behaviour
that it is stored correctly

### Steps to reproduce
edit wiki and save

### Configuration

- Kanboard version:1.2.21
- Database type and version:mysql 5.6.47
- PHP version:8.1.2
- OS: Win
- Browser: Firefox
- Application settings Language: Es

**Comment by lastlink** [comment]
@carlosnewmusic **what version** of the plugin are you using? likely this is a file encoding issue. I've encoded it to utf8. if you have special characters sometimes the table in mysql has to be updated to support them.

function version_7(PDO $pdo){
    $pdo->exec("ALTER TABLE wikipage CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;");
    $pdo->exec("ALTER TABLE wikipage_editions CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;");
}

**Comment by carlosnewmusic** [comment]
> ALTER TABLE wikipage CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;

no such table exists in the database :(

**Comment by lastlink** [comment]
what version of the plugin are you using? also the wikipage table must exist for the plugin to even work.

**Comment by lastlink** [comment]
I might recommend reinstalling the extension, dropping any wiki tables and looking for the migrations table to remove entries

**Comment by carlosnewmusic** [comment]
> what version of the plugin are you using? also the wikipage table must exist for the plugin to even work.

0.3.0 at the time, I have now updated it; Can't the content of the old tables be migrated to the new tables?

**Comment by lastlink** [comment]
I might recommend reaching out for technical help on https://kanboard.discourse.group/c/plugins/8. I don't have enough info on your setup to help you. It probably some kind of foreign language special character encoding.

**Comment by lastlink** [comment]
looks like solution to update the character set yet again to support emojis.
https://kanboard.discourse.group/t/wiki-plugin-error-message-when-save-page-with-emojis/2357/6
I might push this out next month unless someone else gets a pr in. I'd have to test it in several databases to verify.
