### ISSUE TITLE
can't find wiki entrance link

### ISSUE THREAD

**Issue by raypp** [funktechno/kanboard-plugin-wiki#4]
as you mentioned on READEME page:

> This section is available from project settings page: **Project > Wiki**. There is also a shortcut from the drop-down menu on the board.

I can't find these links in my project page.

**Comment by lastlink** [comment]
I added an image to the link in the readme.

![Wiki link](https://raw.githubusercontent.com/funktechno/kanboard-plugin-wiki/master/Asset/images/kanboard-wiki-link.png)
