### ISSUE TITLE
No way to access files attached from wiki page?

### ISSUE THREAD

**Issue by RainerBielefeld** [funktechno/kanboard-plugin-wiki#41]
This issue is:  
- [x] Bug report

I have a problem with access to attachments for Wiki pages, for details please see [this discussion](https://kanboard.discourse.group/t/wiki-plugin-for-kanboard-attachment-handling/2327)!

Any known solutions?

**Comment by lastlink** [comment]
@RainerBielefeld  file attachments seem to be working, could you share a screenshot?

**Comment by lastlink** [comment]
@RainerBielefeld you didn't share your plugin version used.
KANBOARD Application version: 1.2.22 on [all-inkl.com](http://all-inkl.com/)
PHP version: 7.4.28
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.15.0-177-generic
Database driver: mysql
Database version: 5.7.37-nmm1-log
[Plugins](https://kanboard.org/plugins.html):
[Wiki 3](https://github.com/funktechno/kanboard-plugin-wiki)
[ProjectInvitation](https://github.com/ipunkt/KanboardProjectInvitation)
[MarkdownPlus](https://github.com/creecros/MarkdownPlus)
[Task2Pdf 1](https://github.com/creecros/Task2pdf)
[Plugin Registration v1.0.8 1](https://github.com/kanboard/plugin-registration/)
[Paste image to markdown](http://.../) 1.0.3,
[KanboardSearch 1](https://github.com/ipunkt/KanboardSearch)
TaskProgressBar
Browser: SeaMonkey (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)

a while back file uploads weren't finished, but were finished in pr https://github.com/funktechno/kanboard-plugin-wiki/pull/19.
looking at your debug log error message this is probably from an older version of the plugin.

**Comment by lastlink** [comment]
PHP Fatal error:  Uncaught Error: Class 'Kanboard\Plugin\Wiki\Model\FileModel' not found in /www/htdocs/w0075f62/tickets.kanban.bielefeldundbuss.de/plugins/Wiki/Model/WikiFile.php:11
Stack trace:
version 0.3.0 by 0.2.5.
0.2.5 probably doesn't have working file attachments. I'd update to latest
