### ISSUE TITLE
Wiki search pages?

### ISSUE THREAD

**Issue by biffbaxter** [funktechno/kanboard-plugin-wiki#5]
So not really a bug of course - but the ability to search the pages of course would be huge if there was any thoughts of using the wiki pages as a bigger part of documentation. 

Did not see search on the roadmap (or filter, etc for wiki pages)....Any thoughts?

**Comment by lastlink** [comment]
Interesting suggestion. I was mostly basing it off of taigaio's wiki support, but also similar to readme wiki's like github wiki. I'm not aware of them using filters or searching, basically you place links in a home page & users use that to navigate. This is supposed to be a wiki to support a project, do you think that user's would have a large wiki for a single project that searching would help?

If I can justify it, I could add it to my roadmap.

**Comment by biffbaxter** [comment]
Really thinking of wikis across all projects (pages in each project of course but searchable globally)- For example I typically have 20+ active projects, I also keep daily logs of work for misc things that come up. If I could search at the global level (like you can for comments) then I can see every wiki page instance that has certain things I might be looking for. (names, notes, calls with people, etc).

**Comment by lastlink** [comment]
I may be able to see the value in globally searching for wiki pages. I'm curious on which search bar I would extend. How are you searching for comments? The top right lets you search for projects & the middle search bar for tasks. Which search bar are you using to search for comments then?

**Comment by biffbaxter** [comment]
In the middle search window you can enter several filters 

comment:"value"
description""value" 

and some others...but in my experience the "comment" search globally looked across all items for comments that matched.

**Comment by lastlink** [comment]
ok I was able to get the comment search to work, from what I can tell this allows you to search tasks that have a comment containing that value. Wikipages are in no way linked to tasks so this search bar is not extendible for this purpose. I know that you can search by the activity bar so it would go back to if kanboard lets me extend for a global wikipage search. I haven't seen any other plugins that do this, but this would require investigation into adding a 3nd search to the global middle search. e.g. tasks, activity search, wiki search.

I'll mark it as pending and when I get around to updating the file attachements & support for reordering the sidebar I'll give it further investigation. I plan to work on these by the end of the year.
