### ISSUE TITLE
"Undefined variable $not_editable" php warnings in kanboard wiki page

### ISSUE THREAD

**Issue by nya1** [funktechno/kanboard-plugin-wiki#56]
This issue is:

- [x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
Many PHP warnings are displayed in Kanboard web app

### Expected behaviour
No warnings are displayed

### Steps to reproduce

1. Run Kanboard 1.2.25 `docker run -e PLUGIN_INSTALLER=true -d --name kanboard -p 80:80 -t kanboard/kanboard:v1.2.25`
2. Install kanboard-plugin-wiki via Plugin installer UI (web app)
3. navigate to project, open wiki

### Screenshots
![example](https://user-images.githubusercontent.com/16636743/205929784-75ac7a9d-cfd4-4c96-bd59-a36898501398.png)

### Logs

```
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/show.php on line 6"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/show.php on line 60"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 1"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 6"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 38"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 39"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 55"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 67"
PHP message: PHP Warning:  Undefined variable $not_editable in /var/www/app/plugins/Wiki/Template/wiki/detail.php on line 95"
```

### Configuration

- Kanboard version: 1.2.25
- Plugin version: 0.3.2
- Database type and version: sqlite
- PHP version: 8.1.12
- OS: Linux 5.4
- Browser: Chrome
- Application settings Language: English

**Comment by tnsfk309** [comment]
same here

**Comment by vlad34** [comment]
same here ^^

**Comment by jlkDE** [comment]
I took a quick glance at the update and came up with the following:

The variable `$not_editable` seems to be part of commit 695f148 which implemented a public mode for the wiki via settings this to `true`, but in the respective methods when viewing pages logged in the variable is not set to `false` (or maybe it should have been set by default, I have no real idea of PHP in general or Kanboard plugins).

Therefore I came up with the following patch, but as I have no knowledge of this I cannot give you a guarantee that this fixes the error for good:

#57

Please also note that the same applies to the variable `$no_layout`, but that one causes no error and it seems to make no difference to negate it explicitly.

**Comment by iulian-radu-at** [comment]
I confirm that applying @jlkDE changes locally my Wiki plugin works again.
So maybe we can speed up the code review process and merge the code (if it is OK) as soon as possible.
Thanks

**Comment by WebProviderNGO** [comment]
Thank you your solution helps to remove the error! But unfortunately, after that, the buttons of the main menu, the project menu, do not work. And when you click on notifications, it goes to another page.
