### ISSUE TITLE
Fatal error on WikiFileController.php

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [funktechno/kanboard-plugin-wiki#59]
This issue is:

- [ x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
Hello all,

First of all, I'd like to thank you for this great plugin.

When I try to click on 'Attach a document' button on a wiki page, I receive an error message on the modal interface, which I paste below:

`Fatal error: Uncaught Error: Call to undefined method Kanboard\Helper\TextHelper::phpToBytes() in /var/www/html/kanboard/plugins/Wiki/Controller/WikiFileController.php:53 Stack trace: #0 /var/www/html/kanboard/app/Core/Controller/Runner.php(77): Kanboard\Plugin\Wiki\Controller\WikiFileController->create() #1 /var/www/html/kanboard/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #2 /var/www/html/kanboard/index.php(9): Kanboard\Core\Controller\Runner->execute() #3 {main} thrown in /var/www/html/kanboard/plugins/Wiki/Controller/WikiFileController.php on line 53
`
### Expected behaviour

I should see the file upload interface.

### Steps to reproduce

Come to an existing wiki page, click on 'Attach a document'.

### Screenshots
![image](https://github.com/funktechno/kanboard-plugin-wiki/assets/7395916/0debb363-841f-4b12-86c3-e22764ca8e99)

### Logs
I've just turned on the debug mode. So, if I'd reach logs, I'll share them here.

### Configuration

- Kanboard version: 1.2.28
- Plugin version: 0.3.2
- Database type and version: PostgreSQL 15.3 (Ubuntu 15.3-1.pgdg22.04+1)
- PHP version: 8.1.18
- OS: Manjaro Linux Xfce
- Browser: Firefox 113.0 (64-bit)
- Application settings Language: English

**Comment by orkutmuratyilmaz** [comment]
I've upgraded to Kanboard V 1.2.29, but the bug is still there.

**Comment by creecros** [comment]
Use the master repo.

**Comment by orkutmuratyilmaz** [comment]
Thanks for your comment @creecros:)

Can you add the fix to a new release? Because I've installed the plugin with plugin manager.

Best,
Orkut

**Comment by orkutmuratyilmaz** [comment]
Also, I've just checked the file at the master repo and it doesn't have your commits. I guess the branches are not merged.

`            'max_size' => $this->helper->text->phpToBytes(get_upload_max_size()),`

https://github.com/funktechno/kanboard-plugin-wiki/blob/master/Controller/WikiFileController.php

**Comment by orkutmuratyilmaz** [comment]
> Use the master repo.
> 
> As I fixed that on March 29th. Haven't seen a new release though.
> 
> [4f96c32](https://github.com/funktechno/kanboard-plugin-wiki/commit/4f96c32a0bdcbe3f86427014a491eb91f71310cd)

I've downloaded the dev branch into my plugins directory, problem is solved by this way. I guess that, this commits deserves a merge:)

Thanks for everything.

Best,
Orkut
