### ISSUE TITLE
A entry in <div class="views-switcher-component">

### ISSUE THREAD

**Issue by polymeer** [funktechno/kanboard-plugin-wiki#61]
**Thank you for creating this super usefull plugin!**

This issue is:

- [ ] Bug report
- [x] Feature request
- [x] Improvement

### Actual behaviour
The entry ```Wiki``` is just visible in ```Projectsettings```

![grafik](https://github.com/funktechno/kanboard-plugin-wiki/assets/7642857/ded19fef-7e6c-467e-b2af-a638f6a93eb8)

### Expected behaviour
I would like to have an separate entry in the top row as ```Overview```, ```Board```, ```Calendar```, ```Gantt```... for quick access and visibility.

![grafik](https://github.com/funktechno/kanboard-plugin-wiki/assets/7642857/3d08aabb-00c3-44f4-bc3e-281175b8d634)

### Configuration

- Kanboard version: 1.2.32
- Plugin version: 0.32 with [patch from alfredbuehler commented on 12.08.2023](https://github.com/funktechno/kanboard-plugin-wiki/issues/60)
- Database type and version: MariaDB 10.5.22
- PHP version: 8.1.24
- OS: Alma 8.8
- Browser: any
- Application settings Language: any

Thank you in advance for your support.

**Comment by lastlink** [comment]
prs are welcome

**Comment by lastlink** [comment]
I'm worried about this making the main list too cluttered. Idk if all users would prefer to have it added to this menu.

**Comment by alfredbuehler** [comment]
It looks quite good, I wouldn't call it cluttered.
![image](https://github.com/user-attachments/assets/b67c48b7-4651-4f5e-b85e-df5ec8e3b34a)

**Comment by lastlink** [comment]
Should be fine to add then.

**Comment by polymeer** [comment]
Thank you all for this improvement. Good job buddies. :ok_hand:

**Comment by polymeer** [comment]
Hello folks,

is it annoying if adding or changing an wiki page also gives a notification?
I have members in KB who usually read the notification email and just work in KB if a interesting on pops up. I start to write down noticeable documentation in wiki pages but nobody will informed about changes or new pages.

I could by a crate of beer. In best case if i got a donation receipt for tax purposes ;-)

Thank you in advance
T
