### ISSUE TITLE
Unable to upload files, check the permissions of your data folder.

### ISSUE THREAD

**Issue by orkutmuratyilmaz** [funktechno/kanboard-plugin-wiki#63]
Hello and thanks for this great repo:)

This issue is:

- [ x] Bug report
- [ ] Feature request
- [ ] Improvement

### Actual behaviour
When I try to upload a pdf file to the wiki, I receive the message below:

`Unable to upload files, check the permissions of your data folder.`

I'm checking the permissions and ownership settings, but nothing's wrong.

Also, I've tried to upload the same file to a task on a board, it worked well.

What can be the reason for this issue?

Best,
Orkut

### Configuration

- Kanboard version: main branch 
- Plugin version: 0.3.3 (master branch)
- Database type and version: PostgreSQL 15.6 (Ubuntu 15.6-1.pgdg22.04+1)
- PHP version:  8.1.27
- OS: Ubuntu 22.04
- Browser: Firefox
- Application settings Language: English

**Comment by lastlink** [comment]
@orkutmuratyilmaz new release out with several fixes. Is this still an issue?

**Comment by orkutmuratyilmaz** [comment]
It works now! Thanks for the new release:)
