### ISSUE TITLE
Get error with Japanese character when create wiki page

### ISSUE THREAD

**Issue by sanokenichiro** [funktechno/kanboard-plugin-wiki#7]
This issue is:

- [x] Bug report
- [ ] Feature request
- [x] Improvement

### Actual behaviour
Cannot use Japanese character to write wiki page.
I am using MySQL for Kanboard.
I can use Japanese character in Kanboard. (Project, Task, Comment, etc...)

### Expected behaviour
Japanese character will available in wiki.

### Screenshots
![image](https://user-images.githubusercontent.com/38994521/41691547-1179cac4-7536-11e8-905f-308712ec7e3e.png)

![image](https://user-images.githubusercontent.com/38994521/41691563-2254530a-7536-11e8-91c5-d7712697d38a.png)

### Configuration

- Kanboard version: 1.2.4
- Database type and version: MySQL5.7.22
- PHP version:5.6.36
- OS:CentOS7.3
- Browser: IE / Chrome

**Comment by lastlink** [comment]
Are you able to use Japanese characters in other parts of kanboard? Like for stories/tasks

**Comment by sanokenichiro** [comment]
あいうえお
テスト
漢字

Thank you,

**Comment by lastlink** [comment]
Seems like I need utf8 encoding to support these. Next update should have this.

**Comment by lastlink** [comment]
Should be working with version 0.2.7 on a mysql instance. I tested postgres & sqlite & they didn't have this issue. Had to do with the table encoding for mysql that needed to be updated.
