### ISSUE TITLE
Uncaught Error: Class "Kanboard\Plugin\Wiki\Model\Wiki" not found

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [funktechno/kanboard-plugin-wiki#91]
Hi,

If you enter the Wiki overview from the settings menu (top right corner), an error occours:

Fatal error: Uncaught Error: Class "Kanboard\Plugin\Wiki\Model\Wiki" not found in /var/www/app_kanboard/vendor/funktechno/kanboard-plugin-wiki/Template/wiki_list/sort_menu.php:5

This is due to classnames that are called in the following file but not available since 0.3.7:

https://github.com/funktechno/kanboard-plugin-wiki/blob/master/Template/wiki_list/sort_menu.php

Changing it from "Wiki" to "WikiModel" solves it.

Also, the missing class is found in use statements here:

https://github.com/funktechno/kanboard-plugin-wiki/blob/9cc54e2c180b2d6fc085967bb9417a53314e6b02/Model/WikiFileModel.php#L6

https://github.com/funktechno/kanboard-plugin-wiki/blob/9cc54e2c180b2d6fc085967bb9417a53314e6b02/Helper/WikiHelper.php#L6

Not sure if they are needed at all. Especially the latter seems wrong anyway, as there's no such class in kanboard itself.

### Configuration

- Kanboard version: 1.2.38
- Plugin version: 0.3.7
- Database type and version: MariaDB 10.4.34
- PHP version: 8.2.20

**Comment by alfredbuehler** [comment]
Thanks for reporting. I also stumbled upon this issue. 
It should now be fixed in the dev branch.
